FROM ubuntu:20.04

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y python3-sphinx make

#RUN apt-get install -y python3 python3-pip
#RUN pip3 install numpy matplotlib sphinx-autobuild
#COPY files/ /root/
#COPY build.sh /root/

#CMD ["/bin/sh", "/root/build.sh"]
